import type { Metadata } from "next";
import "./globals.css";
import ROOT_HOOKS from "@/hooks/hooks_component/ROOT_HOOKS";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <ROOT_HOOKS>
        <body >
          {children}
        </body>
      </ROOT_HOOKS>
    </html>
  );
}
